### ISSUE TITLE
Listener crash when group is empty

### ISSUE THREAD

**Issue by it25fg** [it25gmbh/plucs#18]
When an xmpp-enabled group turns out to have no xmpp-enabled users the following traceback appears:

> Traceback (most recent call last):
>  File "/usr/lib/univention-directory-listener/system/plucs-groups.py", line 134, in handler
>     _write_groups_config()
>  File "/usr/lib/univention-directory-listener/system/plucs-groups.py", line 197, in _write_groups_config
>     for u in _cache['groups'][g]:

**Comment by it25fg** [comment]
Listener should handle this condition as it can be normal if:
- a group was freshly created (without users) or xmpp-enabled
- all members of a given group are currently xmpp-disabled.
